import type { Annotation, Case } from "./compare-sast-score.mts";
import type { Tool } from "./compare-sast-tools.mts";
import { languages, tools } from "./compare-sast-tools.mts";

// Renders the comparison as Markdown. A tool counts only for the languages it
// analyzes; elsewhere it is "n/a" rather than a miss.

const groups: Readonly<Record<string, readonly string[]>> = {
  Direct: ["direct"],
  "Same-file wrapper": ["sink-wrapper", "source-wrapper"],
  "Cross-file wrapper": ["sink-wrapper-file", "source-wrapper-file"],
  "Safe (flagged)": ["safe-constant", "safe-api"],
};

const shapeOf = (entry: Case) => entry.name.split("-").slice(1).join("-");

function covers(tool: Tool, language: string): boolean {
  return tool.sources.some(
    (source) => source.language === null || source.language === language,
  );
}

function ratio(tool: Tool, cases: readonly Case[]): string {
  const applicable = cases.filter(
    (entry) => covers(tool, entry.language) && entry.tools[tool.name] !== null,
  );
  if (applicable.length === 0) return "n/a";
  const flagged = applicable.filter(
    (entry) => (entry.tools[tool.name] ?? []).length > 0,
  );
  return `${flagged.length}/${applicable.length}`;
}

function row(cells: readonly string[]): string {
  return `| ${cells.join(" | ")} |`;
}

function header(first: string): string[] {
  const names = tools.map((tool) => tool.name);
  return [row([first, ...names]), row(["---", ...names.map(() => "---:")])];
}

function summary(cases: readonly Case[]): string[] {
  const lines = header("Cases");
  for (const [group, shapes] of Object.entries(groups)) {
    const selected = cases.filter((entry) => shapes.includes(shapeOf(entry)));
    lines.push(row([group, ...tools.map((tool) => ratio(tool, selected))]));
  }
  return lines;
}

function byLanguage(cases: readonly Case[]): string[] {
  const lines = header("Vulnerable found / safe flagged");
  for (const language of languages) {
    const own = cases.filter((entry) => entry.language === language);
    const cells = tools.map((tool) => {
      if (!covers(tool, language)) return "n/a";
      if (own.every((entry) => entry.tools[tool.name] === null))
        return "not run";
      const found = ratio(
        tool,
        own.filter((entry) => entry.vulnerable),
      );
      const flagged = ratio(
        tool,
        own.filter((entry) => !entry.vulnerable),
      );
      return `${found} · ${flagged}`;
    });
    lines.push(row([language, ...cells]));
  }
  return lines;
}

function details(cases: readonly Case[]): string[] {
  const lines = header("Case");
  for (const entry of cases) {
    const cells = tools.map((tool) => {
      if (!covers(tool, entry.language)) return "n/a";
      const rules = entry.tools[tool.name];
      if (rules === null || rules === undefined) return "not run";
      return rules.length > 0 ? rules.join(", ") : "–";
    });
    const label = `${entry.language}/${entry.name}${entry.vulnerable ? "" : " (safe)"}`;
    lines.push(row([label, ...cells]));
  }
  return lines;
}

const key = (entry: Annotation) =>
  `${entry.language}/${entry.file}:${entry.line}`;

interface Model {
  readonly model: string;
  readonly hits: readonly string[];
}

function fixtures(
  expected: readonly Annotation[],
  models: readonly Model[],
): string[] {
  const lines = [
    row([
      "Language",
      "Unsafe lines",
      "Safe lines",
      ...models.map((m) => `CodeQL ${m.model}`),
    ]),
    row(["---", "---:", "---:", ...models.map(() => "---:")]),
  ];
  for (const language of languages) {
    const own = expected.filter((entry) => entry.language === language);
    const unsafe = own.filter((entry) => entry.vulnerable);
    const safe = own.filter((entry) => !entry.vulnerable);
    const cells = models.map(({ hits }) => {
      if (language === "go") return "not buildable";
      const found = unsafe.filter((entry) => hits.includes(key(entry))).length;
      const flagged = safe.filter((entry) => hits.includes(key(entry))).length;
      return `${found} found · ${flagged} flagged`;
    });
    lines.push(
      row([language, String(unsafe.length), String(safe.length), ...cells]),
    );
  }
  return lines;
}

export function markdown(
  cases: readonly Case[],
  expected: readonly Annotation[],
  models: readonly Model[],
  versions: string,
): string {
  return [
    "# SAST comparison results",
    "",
    "Generated by `scripts/compare-sast.sh`.",
    "",
    "```text",
    versions.trim(),
    "```",
    "",
    "## Neutral corpus by case shape",
    "",
    ...summary(cases),
    "",
    "## Neutral corpus by language",
    "",
    ...byLanguage(cases),
    "",
    "## CodeQL on the Opengrep fixtures",
    "",
    ...fixtures(expected, models),
    "",
    "## Every case",
    "",
    ...details(cases),
    "",
  ].join("\n");
}
