import assert from "node:assert/strict";
import { writeFile } from "node:fs/promises";

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

const source = "https://spdx.org/licenses/licenses.json";
const response = await fetch(source, { signal: AbortSignal.timeout(30_000) });
assert.ok(response.ok, `SPDX request failed: HTTP ${response.status}`);
const data: unknown = await response.json();
assert.ok(isRecord(data), "Invalid SPDX license list");
const version = data["licenseListVersion"];
assert.ok(typeof version === "string" && /^[\d.]+$/u.test(version));
assert.ok(Array.isArray(data["licenses"]), "Missing SPDX licenses");

const entries: unknown[] = data["licenses"];
const allowed = new Set<string>();
for (const entry of entries) {
  assert.ok(isRecord(entry), "Invalid SPDX license entry");
  assert.ok(typeof entry["isOsiApproved"] === "boolean");
  if (!entry["isOsiApproved"]) continue;
  const id = entry["licenseId"];
  // Grant interprets globs, so only accept literal SPDX identifiers.
  assert.ok(typeof id === "string" && /^[A-Za-z0-9.+-]+$/u.test(id));
  allowed.add(id);
}
assert.ok(allowed.size > 0, "Refusing to write an empty license policy");

const policy = [
  "# Generated by task maintenance:licenses; review changes before committing.",
  `# SPDX License List ${version}: ${source}`,
  "# Only IDs marked isOsiApproved; no wildcard or package exemptions.",
  "require-license: true",
  "require-known-license: true",
  "allow:",
  ...[...allowed].toSorted().map((id) => `  - ${id}`),
  "",
].join("\n");

await writeFile(new URL("../.grant.yaml", import.meta.url), policy);
console.log(
  `Updated OSI policy from SPDX ${version}: ${allowed.size} licenses.`,
);
