[package]
name = "word-count"
version = "0.1.0"
edition = "2024"
license = "Unlicense"
publish = false

[lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"
unused_lifetimes = "warn"
unused_qualifications = "warn"

[lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
dbg_macro = "warn"
todo = "warn"
unimplemented = "warn"
unwrap_used = "warn"
expect_used = "warn"
undocumented_unsafe_blocks = "warn"
allow_attributes_without_reason = "warn"
